raptor2: Don't define vsnprintf in VC++.
win32_rasqal_config.h was defining vsnprintf to _vsnprintf, but then
stdio.h tried to declare both, and the macro made it declare the latter
twice instead. This commit adds a patch to remove the vsnprintf #define.
It's only applied on MSVC, because I don't know if MinGW is affected.

Fixes build error:
Include\stdio.h(358) : error C3163: '_vsnprintf': attributes inconsistent
with previous declaration
Include\stdio.h(350) : see declaration of '_vsnprintf'